# Generated by Django 3.1rc1 on 2020-08-05 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200805_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_at',
            new_name='created',
        ),
    ]
